# Generated by Django 4.1 on 2022-09-27 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='email',
            new_name='contact_email',
        ),
    ]
