# Generated by Django 4.1 on 2022-10-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_email_contactmodel_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='message',
            field=models.CharField(max_length=250),
        ),
    ]
