# Generated by Django 4.1 on 2022-10-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactmodel_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='contact_email',
            field=models.EmailField(max_length=50),
        ),
    ]
